---
- name: Notify UNIX Admin of Hostname Update and Reboot
  hosts: all
  become:  no
  vars:
    email_to: "greg.wright@rackroom.com"
    email_subject: "{{ ansible_hostname }} was successfully updated and rebooted"
    email_body: "The hostname {{ ansible_hostname }} has been successfully updated and the system has been rebooted."

  tasks:
    - name: Send email notification
      ansible.builtin.mail:
        host: localhost
        port: 25
        to: greg.wright@rackroom.com
        subject: "Server Reboot Successful"
        body: "The server {{ inventory_hostname }} was rebooted successfully."
