---
- name: Notify UNIX Admin of Hostname Update and Reboot
  hosts: all
  become:  yes
  vars:
    email_to: "greg.wright@rackroom.com"
    email_subject: "{{ ansible_hostname }} was successfully updated and rebooted"
    email_body: "The hostname {{ ansible_hostname }} has been successfully updated and the system has been rebooted."

  tasks:
    - name: Send email notification
      community.general.mail:
        to: "{{ email_to }}"
        subject: "{{ email_subject }}"
        body: "{{ email_body }}"
