
---
- name: Notify server reboot success
  hosts: all
  become: yes
  vars:
    email_to: "unix_admin@rackroom.com"
    subject: "Server Reboot Successful"
  tasks:
    - name: Get hostname
      ansible.builtin.command: hostname
      register: hostname_result

    - name: Send email notification
      community.general.mail:
        to: "{{ email_to }}"
        subject: "{{ subject }}"
        body: |
          The server {{ hostname_result.stdout }} has rebooted successfully.
