---
- name: Check if reboot is needed and reboot if necessary
  hosts: all
  become: true
  tasks:

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: Reboot the system if needed
      ansible.builtin.reboot:
        msg: "Rebooting due to updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists
