---
- name: Update all packages
  #hosts: clients
  hosts: "{{ target_hosts }}"
  become: yes
  tasks:
    - name: Update all packages to the latest version
      yum:
        name: '*'
        state: latest

    - name: Check if reboot is required
      register: reboot_required
      command: needs-restarting -r
      ignore_errors: yes

    - name: Reboot if necessary
      reboot:
      when: reboot_required.rc == 0
